#! /bin/sh

# bspwm hotkeys
#

ctrl + alt + a
    bash /home/schism/.config/scripts/user-auth.sh

super + ctrl + alt + shift
    pkill x

super + shift + q
    bspc quit

super + q
    bspc node -c

super + t
    bspc desktop -l next

super + b
    bspc desktop -B

super + {s,f}
    bspc node -t {floating,fullscreen}

#super + {grave,Tab}
#    bspc {window,desktop} -f last

# Presel window for splitting
alt + ctrl + {h,j,k,l}
	bspc node -p {left,down,up,right}

alt + Tab
	bspc node -f next

super + apostrophe
    bspc node -s last

super + {o,i}
    bspc control --record-history off; \
    bspc node {older,newer} -f; \
    bspc control --record-history on

super + y
    bspc node -w last.manual

super + m
    bspc node -s biggest

super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {left,down,up,right}

super + {_,shift + }c
    bspc node -f {next,prev}

super + {comma,period}
    bspc desktop -C {backward,forward}

super + bracket{left,right}
    bspc desktop -f {prev,next}

super + ctrl + {h,j,k,l}
    bspc node -p {left,down,up,right}

super + ctrl + {_,shift + }space
    bspc {node -p cancel,desktop -c}

super + alt + {h,j,k,l}
    bspc node -e {left,down,up,right} push

super + alt + shift + {h,j,k,l}
    bspc node -e {right,up,down,left} pull

super + ctrl + {1-9}
    bspc node -r 0.{1-9}

super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} ^{1-9,10}

~button1
    bspc pointer -g focus

super + button{1-3}
    bspc pointer -g {move,resize_side,resize_corner}
    
super + !button{1-3}
   bspc pointer -t %i %i

#alt + {_, shift} + bracketright
#	bspc config -d focused right_padding $((`bspc config -d focused right_padding` {+,-} 20 ))

#alt + {_, shift} + bracketleft
#	bspc config -d focused left_padding $((`bspc config -d focused left_padding` {+,-} 21 ))

#ctrl + {_, shift} + bracketright
#	bspc config -d focused bottom_padding $((`bspc config -d focused bottom_padding` {+,-} 20 ))

#ctrl + {_, shift} + bracketleft
#	bspc config -d focused top_padding $((`bspc config -d focused top_padding` {+,-} 20 ))

alt + shift + {minus,equal}
        bspc config -d focused right_padding $((`bspc config -d focused right_padding` {+,-} 20 )); \
	bspc config -d focused left_padding $((`bspc config -d focused left_padding` {+,-} 20 )); \
	bspc config -d focused bottom_padding $((`bspc config -d focused bottom_padding` {+,-} 20 )); \
	bspc config -d focused top_padding $((`bspc config -d focused top_padding` {+,-} 20 ));

alt + {minus,equal}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 2 ))

#
# wm independent hotkeys\n^ro(${DC6})^ib(1)^pa(2)ver. 0.1")\
#

alt + t
    urxvt

alt + r
#    dmenu_run -fn "-xos4-terminus-medium-r-*-*-28-*"
        gmrun
alt + f
	thunar
	
alt + w
	google-chrome-unstable	

super + shift + w
        firefox
	
alt + s
	scrot

ctrl + alt + s
	scrot -u -q 100 

alt + shift + s
	scrot -s
	
super + a
	exec ~/.wm_scripts/menu
	
super + F12
	amixer -q set Master 5%+ unmute

super + F11
	amixer -q set Master 5%- unmute
	
super + F10
	amixer -q set Master mute

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd
