#!/bin/sh

bspc config border_width        2
bspc config window_gap          25

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x} \
    let i++
done
NMON=$i
unset i

bspc config top_padding 50  # <-- originally for smaller monitor

# Visual options
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel			true
bspc config normal_border_color		"#282829"
bspc config active_border_color		"#535C5C"
bspc config focused_border_color	"#535C5C"
bspc config presel_border_color		"#9a875f"
bspc config urgent_border_color 	"#9f7155"
bspc config focused_locked_border_color	"#9a875f"
bspc config normal_frame_opacity	0.0
bspc config focused_frame_opacity	0.1


# Rules
bspc rule -a mumble 			floating=on desktop=^3
bspc rule -a skype 			floating=on manage=on desktop=^3
bspc rule -a spotify 			desktop=^4
bspc rule -a thunar 			floating=on
bspc rule -a transmission-gtk 		pseudo_tiled=on
bspc rule -a steam 			floating=on desktop=^4
bspc rule -a google-chrome-unstable 	desktop=^2
bspc rule -a chrome 			desktop=^2
#bspc rule -a gimp 			floating=on
bspc rule -a pavucontrol		floating=on
bspc rule -a vlc                        floating=on
bspc rule -a eog			floating=on

conky -c /home/schism/.config/scripts/conky &
sxhkd /home/schism/.config/sxhkd/sxhkdrc &
compton --config ~/.compton.conf &
